// Generated by CoffeeScript 1.4.0
(function() {
  var assert, assertChat, featureName, robot, stagemotron;

  assert = require("assert");

  stagemotron = require("../stagemotron.js");

  robot = require("./support/hubot_mock.js");

  featureName = "feature-branch";

  assertChat = function(expect, done) {
    return function(chatPost) {
      assert.equal(chatPost, expect);
      return done();
    };
  };

  describe('Stagemotron', function() {
    beforeEach(function() {
      return stagemotron('wipe');
    });
    describe('asking for the pipe contents', function() {
      var chat;
      chat = function(name) {
        name || (name = featureName);
        return "stagemotron, << " + name;
      };
      return it('resonds with two', function(done) {
        var expect, r, sizeReq;
        sizeReq = "stagemotron, ls";
        expect = "" + featureName + ",another-feature";
        r = robot();
        stagemotron(r.setInput(chat()));
        stagemotron(r.setInput(chat('another-feature')));
        return stagemotron(r.setInput(sizeReq).setChatRoom(assertChat(expect, done)));
      });
    });
    describe('adding a feature to the pipe', function() {
      var chat;
      chat = "stagemotron, << " + featureName;
      it('lets the first feature start', function(done) {
        var expect, r;
        expect = "The staging environment is ready for feature-branch";
        r = robot().setInput(chat).setChatRoom(assertChat(expect, done));
        return stagemotron(r);
      });
      it('tells the second feature to wait', function(done) {
        var expect, firstFeature, r, secondFeature;
        expect = "You're number: 2 in the pipeline";
        firstFeature = "stagemotron, << a-feature";
        secondFeature = "stagemotron, << another-feature";
        r = robot();
        stagemotron(r.setInput(firstFeature));
        return stagemotron(r.setInput(secondFeature).setChatRoom(assertChat(expect, done)));
      });
      return it('increases the pipe length', function(done) {
        var dumpReq, expect, r;
        dumpReq = "stagemotron, dump";
        expect = JSON.stringify({
          pipeline: [
            {
              branch: featureName,
              lsotd: false
            }
          ],
          history: []
        });
        r = robot();
        stagemotron(r.setInput(chat));
        return stagemotron(r.setInput(dumpReq).setChatRoom(assertChat(expect, done)));
      });
    });
    return describe('a user merges master', function() {
      return it('notifies the next feature that they can stage', function(done) {
        var expect, featureSHA, firstFeature, nextFeature, r;
        expect = "The staging environment is ready for next-feature-branch";
        featureSHA = "415364bea630d56e0fc6d6b5449e8faac613992c";
        firstFeature = "stagemotron, << feature-branch";
        nextFeature = "stagemotron, << next-feature-branch";
        r = robot();
        stagemotron(r.setInput(firstFeature));
        stagemotron(r.setInput(nextFeature));
        return stagemotron(r.setInput('/stagemotron').setPayload(JSON.stringify({
          sha: featureSHA
        })).setChatRoom(assertChat(expect, done)));
      });
    });
  });

}).call(this);
