// Generated by CoffeeScript 1.4.0
(function() {
  var pipeline;

  pipeline = [];

  module.exports = function(robot) {
    var newPipeUnit;
    newPipeUnit = function(featureName) {
      return {
        branch: featureName
      };
    };
    if (robot === "wipe") {
      pipeline = [];
      return {};
    }
    robot.hear(/deploymotron, ls/i, function(msg) {
      return msg.send("" + pipeline.map(function(pipeUnit) {
        return pipeUnit.branch;
      }));
    });
    robot.hear(/deploymotron, << (.+)/i, function(msg) {
      var feature;
      feature = msg.match[1];
      pipeline.push(newPipeUnit(feature));
      return msg.send("You're number: " + pipeline.length + " in the pipeline");
    });
    return robot.hear(/deploymotron, dump/i, function(msg) {
      return msg.send(JSON.stringify(pipeline));
    });
  };

}).call(this);
