// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(callback) {
    callback || (callback = function() {});
    return {
      say: function(message) {
        callback(message);
        return message;
      }
    };
  };

}).call(this);
