// Generated by CoffeeScript 1.4.0
(function() {
  var fs, newChatRoom;

  fs = require("fs");

  newChatRoom = require("./chatroom_mock.js");

  module.exports = function() {
    var chatRoom, input, payload, responses;
    responses = [];
    input = null;
    chatRoom = newChatRoom();
    payload = null;
    return {
      setChatRoom: function(chatCallback) {
        chatRoom = newChatRoom(chatCallback);
        return this;
      },
      setInput: function(_input) {
        input = _input;
        return this;
      },
      setPayload: function(_payload) {
        payload = _payload;
        return this;
      },
      hear: function(regex, robotCallback) {
        var match, msg;
        match = input.match(regex);
        msg = {
          send: function(response) {
            return chatRoom.say(response);
          },
          match: match
        };
        if (match) {
          return robotCallback(msg);
        }
      },
      messageRoom: function(message) {
        return chatRoom.say(message);
      },
      router: {
        post: function(urlPath, callback) {
          if (input !== urlPath) {
            return;
          }
          return callback({
            body: {
              payload: payload
            }
          });
        }
      },
      http: function(url) {
        return {
          get: function() {
            return function(callback) {
              var filePath;
              filePath = url.match(/[^\/]+$/)[0];
              return fs.readFile("test/fixtures/" + filePath, function(err, data) {
                return callback(err, {}, data.toString());
              });
            };
          }
        };
      }
    };
  };

}).call(this);
